name: ./airizse
author-description: I'm not a workaholic. I'm just exhausted. (Help me)
meta_description: "Airizse's Internet Bundle"
joke: I would have loved telling you this UDP joke, but you might not get it...

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://airizse.xyz'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'airizse'

# Details for the RSS feed generator
url:            'https://airizse.github.io/'
author:         'Airizse'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

# Site settings
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
# For Sass partials
sass:
    sass_dir: ./assets/css